Repository pluralsh/module-library, pull requests merged in 2023-07, with the labels that each got.

#22 feat(clickhouse): misc refinements
  helm/clickhouse/Chart.yaml
  helm/clickhouse/templates/_clickhouse.tpl
  helm/clickhouse/templates/_helpers.tpl
  helm/clickhouse/templates/clickhouse_instance.yaml
  helm/clickhouse/templates/postinstallhook.yaml
  helm/clickhouse/templates/predeletehook.yaml
  helm/clickhouse/templates/secrets.yaml
  helm/clickhouse/values.yaml
Labels: size/L

#23 fix(clickhouse): correct name for backup script cm
  helm/clickhouse/Chart.yaml
  helm/clickhouse/templates/cronjob-backup-configmap.yaml
Labels: size/XS

#24 feat: add a library chart for runbooks
  helm/runbook/.helmignore
  helm/runbook/Chart.yaml
  helm/runbook/templates/_helpers.tpl
  helm/runbook/templates/_runbooks.tpl
  helm/runbook/values.yaml
Labels: size/L

#25 fix(runbook): use correct query for memory + title cleanup
  helm/runbook/Chart.yaml
  helm/runbook/templates/_runbooks.tpl
Labels: size/S
