Repository pluralsh/module-library, pull requests merged in 2023-06, with the labels that each got.

#18 Improve test base chart
  helm/test-base/Chart.yaml
  helm/test-base/templates/test.yaml
  helm/test-base/values.yaml
Labels: enhancement, size/S

#19 feat: create pre-delete hook for clickhouse installations
  .gitignore
  helm/clickhouse/Chart.yaml
  helm/clickhouse/templates/predeletehook.yaml
  helm/clickhouse/values.yaml
Labels: size/M

#20 fix(clickhouse): use correct template name
  helm/clickhouse/Chart.yaml
  helm/clickhouse/templates/predeletehook.yaml
Labels: size/XS

#21 fix: typo
  helm/clickhouse/Chart.yaml
  helm/clickhouse/templates/predeletehook.yaml
Labels: size/XS
